---
- name: add jenkins-ci.org key
  apt_key: url="https://jenkins-ci.org/debian/jenkins-ci.org.key" state="present"

- name: add jenkins-ci.org repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: update ubuntu packages
  apt: update_cache=yes
  ignore_errors: true

- name: install ubuntu packages
  apt: name="{{item}}" state=present
  with_items:
    - "{{jenkins['packages']['apt']}}"
