---
- name: update ubuntu packages
  apt: update_cache=yes
  ignore_errors: true

- name: install ubuntu packages
  apt: name="{{item}}" state=present
  with_items:
    - "{{minion['packages']['apt']}}"
